close all
clear all
clc


%% input (choose one)

your_choice = 2;
switch (your_choice)

    case 1 % food web -> 0.19        
           % https://www.nceas.ucsb.edu/interactionweb/html/thomps_towns.html 
        G = importdata('./Narrowdaletxt.txt', '\t');
        A = sparse(1*(G>0));
        clear G;
        
    case 2 % food web -> 0.41
           % https://snap.stanford.edu/data/Florida-bay.html 
        G = importdata('./Florida-bay.txt', ' ', 5);
        G.data = G.data + 1;
        N = max(max(G.data));
        A = sparse(G.data(:,2),G.data(:,1),ones(size(G.data,1),1),N,N);
        clear G;

    case 3 % food web -> 0.28
           % https://www.nceas.ucsb.edu/interactionweb/html/carpinteria.html 
        G = importdata('./carpinteria.txt', '	');
        A = sparse(1*(G(1:83,1:83)>0));
        N = size(A,1);
        clear G;

    case 4 % email network -> 0.26
           % https://snap.stanford.edu/data/email-Eu-core.html
        G = importdata('./email-Eu-core.txt', ' ');
        G = G+1;
        N = max(max(G));
        A = sparse(G(:,2),G(:,1),ones(size(G,1),1),N,N);
        clear G;

    case 5 % citation network (reduced size) -> 0.003
           % https://aminer.org/citation 
           % generated by files: 
           %    citation_step1.m = extracts network
           %    citation_step2.m = extracts smaller sub-network
        load('adjacency_matrix2.mat')
        
end


%% pre-processing

Au = 1*(A+A'>0); % undirected network
Au = Au - diag(diag(Au)); % clear diagonal (you never know)

% remove nodes which are NOT connected
pos = find(sum(Au)~=0);
A = A(pos,pos);
Au = Au(pos,pos);
N = size(Au,1);

% ... go on

